server:
  port: 9001
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authservicedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
