
server:
  port: 8084
key:
  name: Notification Service Application Value From Git Hub
  status: Notification Service UP and WORKING from GIT Hub
spring:
  application:
    name: notification-service 
  cloud:    
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 10s
    instances:
      generalRetry:
        baseConfig: default
        waitDuration: 200ms

        
