app:
  jwtSecret: MySuperSecretJwtKeyThatIsAtLeast512BitsLongMySuperSecretJwtKeyThatIsAtLeast512BitsLong
  jwtExpirationInMs: 86400000 # 1 day in milliseconds

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
