
server:
  port: 8084
key:
  name: Notification Service Application Value From Git Hub
  status: Notification Service UP and WORKING from GIT Hub
spring:
  application:
    name: notification-service 
  cloud:    
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - io.github.resilience4j.core.RequestNotPermitted
  retry:
    instances:
      retryBackendA:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - io.github.resilience4j.core.RequestNotPermitted
  ratelimiter:
    instances:
      backendARateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
        eventConsumerBufferSize: 100

        
